<?php

@define ('','');
@define ('','');
@define ('','');
@define ('','');
@define ('','');
@define ('','');
@define ('','');
@define ('','');
@define ('','');
@define ('','');
@define ('','');
@define ('','');
@define ('','');
@define ('','');
@define ('_duannoibat','Dự án nổi bật');
@define ('_hethongloi','Hệ thống bận. Vui lòng thử lại sau.');
@define ('_dangkytaikhoanthanhcong','Đăng ký tài khoản thành công!');
@define ('_emaildaduocsudung','Email đã được sử dụng.');
@define ('_tendangnhapdaduocsudung','Tên đăng nhập đã được sử dụng.');
@define ('_tendangnhapvamatkhaukhongchinhxac','Thông tin đăng nhập không chính xác!');
@define ('_dangnhapthanhcong','Đăng nhập thành công!');
@define ('_dangky','Đăng ký');
@define ('_ten','Họ tên');
@define ('_dangnhap','Đăng nhập');
@define ('_matkhau','Mật khẩu');
@define ('_tendangnhap','Tên đăng nhập');
@define ('_thanhtoan','Thanh toán');
@define ('_capnhat','Cập nhật');
@define ('_xoatatca','Xóa tất cả');
@define ('_muatiep','Mua tiếp');
@define ('_tonggia','Tổng giá');
@define ('_soluong','Số lượng');
@define ('_hinhanh','Hình ảnh');
@define ('_giohang','Giỏ hàng');
@define ('_duankhac','Dự án khác');
@define ('_thongtinchitiet','Thông tin chi tiết');
@define ('_xoa','Xóa');
@define ('_hoten','Họ tên');
@define ('_gioithieuveleman','Giới thiệu về Leman');
@define ('_duan','Dự án');
@define ('_thietke','Thiết kế');
@define ('_dichvu','Dịch vụ');
##
@define ('_timkiem','Tìm kiếm');
@define ('_banchuanhaptukhoa','Bạn chưa nhập từ khóa!');
@define ('_loichaosanphambanchay','Những sản phẩm mới nhất và bán chạy nhất.<br/>Chúng tôi cảm ơn các bạn đã quan tâm và ủng hộ Bách Thuần');
@define ('_xemchitiet','Xem chi tiết');
@define ('_ketquatimkiem','Kết quả tìm kiếm');
@define ('_tintucnoibat','Tin tức nổi bật');
@define ('_danhmucsanpham','Danh mục sản phẩm');
@define ('_danhmuctintuc','Danh mục tin tức');
@define ('_congdung','Công dụng');
@define ('_thanhphan','Thành phần');
@define ('_luotxem','Lượt xem');
@define ('_masp','Mã sản phẩm');
@define ('_gia','Giá');
@define ('_chitietsanpham','Chi tiết sản phẩm');
@define ('_sanphamcungloai','Sản phẩm cùng loại');
@define ('_dangcapnhat','Nội dung đang cập nhật vui lòng quay lại sau!');
@define ('_tintuckhac','Tin tức khác');
@define ('_tongtruycap','Tổng truy cập');
@define ('_dangonline','Đang online');
@define ('_thongketruycap','Thống kê truy cập');
@define ('_gui','Gửi');
@define ('_nhapemail','Nhập email');
@define ('_dangkynhanemail','Đăng ký nhận email');
@define ('_nhaptukhoa','Nhập từ khóa');
@define ('_lienhe','Liên hệ');
@define ('_tuyendung','Tuyển dụng');
@define ('_tintuc','Tin tức');
@define ('_trangtrai','Trang trại');
@define ('_doitac','Đối tác');
@define ('_sanpham','Sản phẩm');
@define ('_gioithieu','Giới thiệu');
@define ('_trangchu','Trang chủ');
@define ('_dangkyemailthanhcong','Đăng ký email nhận tin thành công!');

##
@define ('_hovaten','Họ và tên');
@define ('_diachi','Địa chỉ');
@define ('_dienthoai','Điện thoại');
@define ('_chude','Chủ đề');
@define ('_noidung','Nội dung');
@define ('_gui','Gửi');
@define ('_nhaplai','Nhập lại');
@define ('_trangbantruycapkhongtontai','Trang bạn truy cập không tồn tại.');
@define ('_loikhongtimthaytrang','Lỗi không tìm thấy trang');
@define ('_xinnhaphoten','Vui lòng nhập họ tên!');
@define ('_xinnhaptieude','Vui lòng nhập tiêu đề!');
@define ('_xinnhapnoidung','Vui lòng nhập nội dung!');
@define ('_xinnhapdiachi','Vui lòng nhập địa chỉ!');
@define ('_xinnhapdt','Vui lòng nhập điện thoại!');
@define ('_dtkhonghople','Số điện thoại không hợp lệ!');
@define ('_emailkhonghople','Email không hợp lệ!');
@define ('_xinhaptieude','Vui lòng nhập chủ đề!');
@define ('_xinhapnoidung','Vui lòng nhập nội dung!');

?>