<?php
@define ('_duannoibat','Featured Project');
@define ('_magiamgia','Discount code');
@define ('_thongtinthanhtoan','Payment information');
@define ('_thanhtoankhinhanhang','Payment on delivery');
@define ('_hinhthucthanhtoan','Payment mode');
@define ('_capnhat','Update');
@define ('_xoatatca','Delete all');
@define ('_muatiep','Buy more');
@define ('_xoa','Delete');
@define ('_tonggia','Total price');
@define ('_gia','Price');
@define ('_hinh','Image');
@define ('_tensp','Product name');
@define ('_thutu','No');
@define ('_sanphamcungloai','Sample product');
@define ('_bancothemuasanphamnaytai','You can buy this product at');
@define ('_traloi','Answer');
@define ('_nguoigui','Sender');
@define ('_hethongloi','System error. Please try again later!');
@define ('_guibinhluanthanhcong','Send questions to success!');
@define ('_vuilongnhapcauhoi','Please enter questions!');
@define ('_xemthemnoidung','More Content');
@define ('_xemthem','Read more');
@define ('_banchaytrongtuan','Sellers of the week');
@define ('_huongdanmuahang','Shopping guide');
@define ('_thongtinchitiet','Details');
@define ('_motasanpham','Product Description');
@define ('_thanhtoan','Payments');
@define ('_tieptucmuahang','Continue Shopping');
@define ('_dathemvaogiohang','Product added to cart!');
@define ('_luotdaxem','views');
@define ('_chovaogio','Add to cart');
@define ('_soluong','Quantity');
@define ('_hethang','out of stock');
@define ('_conhang','in stock');
@define ('_trangthai','State');
@define ('_giaban','Price');
@define ('_masp','Product code');
@define ('_dong','Close');
@define ('_xemchitiet','Details');
@define ('_khongcoketquatimkiem','No products matching your request!');
@define ('_tren','Below');
@define ('_duoi','Over');
@define ('_tu','From');
@define ('_khoanggia','Price range');
@define ('_mausac','Color');
@define ('_begai','Girls');
@define ('_betrai','Boys');
@define ('_gioitinh','Gender');
@define ('_timtheo','Search by');
@define ('_giam','Discount');
@define ('_tatcadanhmuc','All categories');
@define ('_trangchu','Home');
@define ('_guicauhoithanhcong','Send questions to success!');
@define ('_tintuckhac','Other news');
@define ('_tinnoibo','Local news');
@define ('_hotro','Support');
@define ('_thanhtichchungnhan','Achievements &amp; Certify');
@define ('_xemtiep','Read more');
@define ('_ketnoivoichungtoi','Connect with us');
@define ('_trogiup','Help');
@define ('_dangkynhantinthanhcong','Newsletter Success!');
@define ('_emaildaduocdangky','Email already registered! Please enter a different email!');
@define ('_moibannhapemail','Please enter your email');
@define ('_nhantinkhuyenmaivaquatang','Receive Promotions &amp; gift');
@define ('_sp','Product');
@define ('_giohang','Cart');
@define ('_tuyendung','Recruitment');
@define ('_thuvien','Library');
@define ('_hethongphanphoi','Distribution System');
@define ('_truyenthong','Media');
@define ('_sanpham','Product');
@define ('_hotrotructuyen247','Support online 24/7');
@define ('_giaohang','Delivery');
@define ('_quytrinh','Process');
@define ('_muahang','Buy');
@define ('_phuongthuc','Method');
@define ('_thuonggap','frequent');
@define ('_cuahang','store');
@define ('_hethong','System');
@define ('_noibo','Local');
@define ('_dangxuatthanhcong','Logout success!');
@define ('_hethongloi','System error! Please try again later!');
@define ('_dangkytaikhoanthanhcong','Account Registration success!');
@define ('_emaildaduocsudung','Email was used.');
@define ('_tendangnhapdaduocsudung','Username was used.');
@define ('_dangxuat','Logout');
@define ('_dangnhapthanhcong','Login successful!');
@define ('_tendangnhapvamatkhaukhongchinhxac','Username and password incorrectly.');
@define ('_ten','Full name');
@define ('_matkhau','Password');
@define ('_tendangnhap','Username');
@define ('_dangky','Register');
@define ('_hethongcuahang','Shop system');
## 04-5-2015
@define ('_bieumau','Form');
@define ('_vanban','Documents');
@define ('_tintuc','News');
@define ('_dangnhapsai','Your username or password incorrect. Please try again!');
@define ('_dangnhap','Login');
@define ('_ketquatimkiem','Search result');
@define ('_timkiem','Search');
@define ('_banchuanhaptukhoa','Please enter the keyword!');
@define ('_nhatkycongtrinh','Project diary');
@define ('_thongtinduan','Project Information');
@define ('_loaicongtrinh','Project type');
@define ('_congtrinhtieubieu','Typical project');
@define ('_congtrinhdathuchien','Executed typical project');
@define ('_congtrinhdangthuchien','In progress project');
@define ('_guicauhoikhongthanhcong','Unsuccessfully! Please try again later!');
@define ('_guicauhoithanhcong','Successfully!');
@define ('_cauhoi','Question');
@define ('_chondanhmuc','Select a category');
@define ('_guicauhoi','Send questions');
@define ('_congtrinhduan','Works project');
@define ('_congty','Company');
@define ('_hoten','Full name');
@define ('_duandenghihoptac','The proposed project collaboration');
@define ('_hinhanh','Images');
@define ('_thongtinlienhe','Contact Information');
@define ('_linhvuchoatdong','Fields of activity');
@define ('_cacduandenghihoptac','The proposed project collaboration');
@define ('_thongtindoitac','Partners Information');
@define ('_doitaccuaeci','ECI Saigon Partners');
@define ('_vuilongdinhkemthuxinviec','Please attaching cover letter!');
@define ('_vuilongdinhkemcv','Please attaching CV!');
@define ('_coloixayra','Error!');
@define ('_nophosothanhcong','Apply success');
@define ('_maxacnhansai','Captcha incorrect!');
@define ('_xinnhapnoidung','Please enter the text!');
@define ('_xinnhapmaxacnhan','Please enter the captcha!');
@define ('_xinnhapvitrituyendung','Please enter the position!');
@define ('_maxacnhan','Captcha');
@define ('_guikemcv','Cover CV');
@define ('_guikemthuxinviec','Attaching cover letter');
@define ('_noilamviec','Working location');
@define ('_donvituyendung','Recruitment agencies');
@define ('_ngayhethan','End date');
@define ('_ngaynophoso','Start Date');
@define ('_tenvitrituyendung','Position');
@define ('_chinhsachtuyendung','Recruitment policy');
@define ('_vitrituyendung','Recruitment position');
@define ('_nophosotructuyen','Online Application');
@define ('_gianhapeci','Joining ECI Saigon');
@define ('_dangcapnhat','Updating...');
##News
@define ('_tintuclienquan','Related News');
## Menu
@define ('_gioithieu','About us');
@define ('_tintucsukien','News &amp; Event');
@define ('_congtrinh','Project');
@define ('_batdongsan','Real estate');
@define ('_tuyendung','Recruitment');
@define ('_doitac','Partners');
@define ('_thongtincodong','Shareholder Information');
@define ('_hoidap','FAQ');
@define ('_lienhe','Contact us');

##Banner
@define ('_tailieutracuu','Reference materials');
@define ('_thongtinnoibo','Internal Information');
@define ('_sodowebsite','Sitemap');

##
@define ('_hovaten','Full name');
@define ('_diachi','Address');
@define ('_dienthoai','Phone');
@define ('_chude','Subject');
@define ('_noidung','Content');
@define ('_gui','Send');
@define ('_nhaplai','Reset');

@define ('_xinnhaphoten','Please enter your name!');
@define ('_xinnhapdiachi','Please enter the address!');
@define ('_xinnhapdt','Please enter the phone!');
@define ('_dtkhonghople','Phone number is invalid!');
@define ('_emailkhonghople','Email is invalid!');
@define ('_xinhaptieude','Please enter the subject!');
@define ('_xinhapnoidung','Please enter the text!');

?>