<?php

@define ('','');
@define ('','');
@define ('','');
@define ('_xembando','Xem bản đồ');
@define ('_duankhac','Dự án khác');
@define ('_giacu','Giá cũ');
@define ('_cao','cao');
@define ('_rong','rộng');
@define ('_dai','dài');
@define ('_chatlieu','Chất liệu');
@define ('_kichthuoc','Kích thước');
@define ('_vietnam','Việt Nam');
@define ('_nuocmy','Nước Mỹ');
@define ('_tongtruycap','Tổng truy cập');
@define ('_dangonline','Đang online');
@define ('_thongketruycap','Thống kê truy cập');
@define ('_chinhsachhotro','Chính sách hỗ trợ');
@define ('_tuvanhotro','Tư vấn hỗ trợ');
@define ('_hethongphanphoi','Hệ thống phân phối');
@define ('_sanphamkhuyenmai','Sản phẩm khuyến mãi');
@define ('_sanphammoi','Sản phẩm mới');
@define ('_duan','Dự án');
@define ('_nhapemailcuaban','Nhập email của bạn');
@define ('_vuilongnhapemaildenhanthongtin','Vui lòng nhập email để nhận thông tin mới nhất từ chúng tôi');
@define ('_dangkynhanemail','Đăng ký nhận email');
@define ('_duocyeuthichnhat','Được yêu thích nhất');
@define ('_hotrobanquantam','Hỗ trợ bạn quan tâm');
@define ('_banquantamnhieunhat','Bạn quan tâm nhiều nhất');
@define ('_videonoibat','Video nổi bật');
@define ('_chitiet','Chi tiết');
@define ('_cauchuyenthanhcong','Câu chuyện thành công');
@define ('_taifiledinhkem','Tải file đính kèm');
@define ('_cothebanquantam','Có thể bạn quan tâm');
@define ('_xemtatca','Xem tất cả');
@define ('_lichtesttienganh','Lịch test tiếng Anh');
@define ('_hocbongduhocmy','Học bổng du học Mỹ');
@define ('_thuvienanh','Thư viện ảnh');
@define ('_thongtinhuuich','Thông tin hữu ích');
@define ('_dangkytuvan','Đăng ký tư vấn');
@define ('_dichvukhac','Dịch vụ khác');
@define ('_tuvanvisamy','Tư vấn visa Mỹ');
@define ('_vuahocvualam','Intership - Vừa học vừa làm');
@define ('_duhocmy','Du học Mỹ');

##
@define ('_thongtindathang','Thông tin đặt hàng');
@define ('_stt','STT');
@define ('_trangbantruycapkhongtontai','Chuyên mục bạn vừa truy cập không tồn tại. Vui lòng xem chuyên mục khác!');
@define ('_loikhongtimthaytrang','Lỗi: không tìm thấy trang');
@define ('_luotxem','Lượt xem');
@define ('_giakhuyenmai','Giá khuyến mãi');
@define ('_chitietsanpham','Chi tiết sản phẩm');
@define ('_danhmuc','Danh mục');
@define ('_nhaptensanpham','Nhập tên sản phẩm');
@define ('_giaohangtoanquoc','Giao hàng toàn quốc');
@define ('_chinhsachquyenriengtu','Chính sách quyền riêng tư');
@define ('_moi','mới');
@define ('_khongcosanphamtronggiohang','Không có sản phẩm trong giỏ hàng!');
@define ('_tukhoalienquan','Từ khóa liên quan');
@define ('_magiamgia','Mã giảm giá');
@define ('_thongtinthanhtoan','Thông tin thanh toán');
@define ('_thanhtoankhinhanhang','Thanh toán khi nhận hàng');
@define ('_hinhthucthanhtoan','Hình thức thanh toán');
@define ('_capnhat','Cập nhật');
@define ('_xoatatca','Xóa tất cả');
@define ('_muatiep','Mua tiếp');
@define ('_xoa','Xóa');
@define ('_tonggia','Tổng giá');
@define ('_gia','Giá');
@define ('_hinh','Hình');
@define ('_tensp','Tên sản phẩm');
@define ('_thutu','Thứ tự');
@define ('_sanphamcungloai','Sản phẩm cùng loại');
@define ('_bancothemuasanphamnaytai','Bạn có thể mua sản phẩm này tại');
@define ('_traloi','Trả lời');
@define ('_nguoigui','Người gửi');
@define ('_hethongloi','Hệ thống lỗi. Vui lòng thử lại sau!');
@define ('_guibinhluanthanhcong','Gửi câu hỏi thành công!');
@define ('_vuilongnhapcauhoi','Vui lòng nhập câu hỏi!');
@define ('_xemthemnoidung','Xem Thêm Nội Dung');
@define ('_xemthem','Xem thêm');
@define ('_banchaytrongtuan','Bán chạy trong tuần');
@define ('_huongdanmuahang','Hướng dẫn mua hàng');
@define ('_thongtinchitiet','Thông Tin Chi Tiết');
@define ('_motasanpham','Mô Tả Sản Phẩm');
@define ('_thanhtoan','Thanh toán');
@define ('_tieptucmuahang','Tiếp tục mua hàng');
@define ('_dathemvaogiohang','Đã thêm sản phẩm vào giỏ hàng!');
@define ('_luotdaxem','lượt đã xem');
@define ('_chovaogio','Cho vào giỏ');
@define ('_soluong','Số lượng');
@define ('_hethang','Hết hàng');
@define ('_conhang','Còn hàng');
@define ('_trangthai','Trạng thái');
@define ('_giaban','Giá bán');
@define ('_masp','Mã sản phẩm');
@define ('_dong','Đóng');
@define ('_xemchitiet','Xem chi tiết');
@define ('_khongcoketquatimkiem','Không có sản phẩm phù hợp với yêu cầu của bạn!');
@define ('_tren','Dưới');
@define ('_duoi','Trên');
@define ('_tu','Từ');
@define ('_khoanggia','Khoảng giá');
@define ('_mausac','Màu sắc');
@define ('_begai','Bé gái');
@define ('_betrai','Bé trai');
@define ('_gioitinh','Giới tính');
@define ('_timtheo','Tìm theo');
@define ('_giam','Giảm');
@define ('_tatcadanhmuc','Tất cả danh mục');
@define ('_trangchu','Trang chủ');
@define ('_guicauhoithanhcong','Gửi câu hỏi thành công!');
@define ('_tintuckhac','Tin tức khác');
@define ('_tinnoibo','Tin nội bộ');
@define ('_hotro','Hỗ trợ');
@define ('_thanhtichchungnhan','Thành tích &amp; Chứng nhận');
@define ('_xemtiep','Xem tiếp');
@define ('_ketnoivoichungtoi','Kết nối với chúng tôi');
@define ('_trogiup','Trợ giúp');
@define ('_dangkynhantinthanhcong','Đăng ký nhận tin thành công!');
@define ('_emaildaduocdangky','Email đã được đăng ký! Vui lòng nhập email khác!');
@define ('_moibannhapemail','Mời bạn nhập email');
@define ('_nhantinkhuyenmaivaquatang','Nhận tin khuyến mãi &amp; Quà tặng');
@define ('_sp','SP');
@define ('_giohang','Giỏ hàng');
@define ('_tuyendung','Tuyển dụng');
@define ('_thuvien','Thư viện');
@define ('_hethongphanphoi','Hệ thống phân phối');
@define ('_truyenthong','Truyền thông');
@define ('_sanpham','Sản phẩm');
@define ('_hotrotructuyen247','Hỗ trợ trực tuyến 24/7');
@define ('_giaohang','Giao hàng');
@define ('_quytrinh','Quy trình');
@define ('_muahang','Mua hàng');
@define ('_phuongthuc','Phương thức');
@define ('_thuonggap','thường gặp');
@define ('_cuahang','cửa hàng');
@define ('_hethong','Hệ thống');
@define ('_noibo','Nội bộ');
@define ('_dangxuatthanhcong','Đăng xuất thành công');
@define ('_hethongloi','Hệ thống bị lỗi vui lòng thử lại sau!');
@define ('_dangkytaikhoanthanhcong','Đăng ký tài khoản thành công!');
@define ('_emaildaduocsudung','Email đã được sử dụng.');
@define ('_tendangnhapdaduocsudung','Tên đăng nhập đã được sử dụng.');
@define ('_dangxuat','Đăng xuất');
@define ('_dangnhapthanhcong','Đăng nhập thành công!');
@define ('_tendangnhapvamatkhaukhongchinhxac','Tên đăng nhập và mật khẩu không chính xác.');
@define ('_ten','Họ và tên');
@define ('_matkhau','Mật khẩu');
@define ('_tendangnhap','Tên đăng nhập');
@define ('_dangky','Đăng ký');
@define ('_hethongcuahang','Hệ thống cửa hàng');
## 04-5-2015
@define ('_bieumau','Biểu mẫu');
@define ('_vanban','Văn bản');
@define ('_tintuc','Tin tức');
@define ('_dangnhapsai','Thông tin đăng nhập không chính xác!');
@define ('_dangnhap','Đăng nhập');
@define ('_thongtincodonglienquan','Thông tin cổ đông liên quan');
@define ('_batdongsanlienquan','Bất động sản liên quan');
@define ('_ecigroup','ECI Group');
## 10-4
@define ('_ketquatimkiem','Kết quả tìm kiếm');
@define ('_timkiem','Tìm kiếm');
@define ('_banchuanhaptukhoa','Bạn chưa nhập từ khóa!');
@define ('_nhatkycongtrinh','Nhật ký công trình');
@define ('_thongtinduan','Thông tin dự án');
@define ('_loaicongtrinh','Loại công trình');
@define ('_congtrinhtieubieu','Công trình tiêu biểu');
@define ('_congtrinhdathuchien','Công trình đã thực hiện');
@define ('_congtrinhdangthuchien','Công trình đang thực hiện');
@define ('_guicauhoikhongthanhcong','Gửi câu hỏi không thành công! Vui lòng thử lại sau!');
@define ('_guicauhoithanhcong','Gửi câu hỏi thành công!');
@define ('_cauhoi','Câu hỏi');
@define ('_chondanhmuc','Chọn danh mục');
@define ('_guicauhoi','Gửi câu hỏi');
@define ('_congtrinhduan','Công trình dự án');
@define ('_congty','Công ty');
@define ('_hoten','Họ tên');
@define ('_duandenghihoptac','Các dự án đề nghị hợp tác');
@define ('_hinhanh','Hình ảnh');
@define ('_thongtinlienhe','Thông tin liên hệ');
@define ('_linhvuchoatdong','Lĩnh vực hoạt động');
@define ('_cacduandenghihoptac','Các dự án đề nghị hợp tác');
@define ('_thongtindoitac','Thông tin đối tác');
@define ('_doitaccuaeci','Đối tác của ECI Sài Gòn');
@define ('_vuilongdinhkemthuxinviec','Vui lòng đính kèm thư xin việc!');
@define ('_vuilongdinhkemcv','Vui lòng đính kèm CV!');
@define ('_coloixayra','Có lỗi xảy ra');
@define ('_nophosothanhcong','Nộp hồ sơ thành công');
@define ('_maxacnhansai','Mã xác nhận không đúng!');
@define ('_xinnhapnoidung','Vui lòng nhập nội dung!');
@define ('_xinnhapmaxacnhan','Vui lòng nhập mã xác nhận!');
@define ('_xinnhapvitrituyendung','Vui lòng nhập vị trí tuyển dụng!');
@define ('_maxacnhan','Mã xác nhận');
@define ('_guikemcv','Gửi kèm CV');
@define ('_guikemthuxinviec','Gửi kèm thư xin việc');
@define ('_noilamviec','Nơi làm việc');
@define ('_donvituyendung','Đơn vị tuyển dụng');
@define ('_ngayhethan','Ngày hết hạn');
@define ('_ngaynophoso','Ngày nộp hồ sơ');
@define ('_tenvitrituyendung','Tên vị trí tuyển dụng');
@define ('_chinhsachtuyendung','Chính sách tuyển dụng');
@define ('_vitrituyendung','Vị trị tuyển dụng');
@define ('_nophosotructuyen','Nộp hồ sơ trực tuyến');
@define ('_gianhapeci','Gia nhập ECI Sài Gòn');
@define ('_dangcapnhat','Nội dung đang cập nhật...');
##News
@define ('_tintuclienquan','Tin tức liên quan');
## Menu
@define ('','');
@define ('_gioithieu','Giới thiệu');
@define ('_tintucsukien','Tin tức &amp; Sự kiện');
@define ('_congtrinh','Công trình');
@define ('_batdongsan','Bất động sản');
@define ('_tuyendung','Tuyển dụng');
@define ('_doitac','Đối tác');
@define ('_thongtincodong','Thông tin cổ đông');
@define ('_hoidap','Hỏi đáp');
@define ('_lienhe','Liên hệ');

##Banner
@define ('_tailieutracuu','Tài liệu tra cứu');
@define ('_thongtinnoibo','Thông tin nội bộ');
@define ('_sodowebsite','Sơ đồ website');
##
@define ('_hovaten','Họ và tên');
@define ('_diachi','Địa chỉ');
@define ('_dienthoai','Điện thoại');
@define ('_chude','Chủ đề');
@define ('_noidung','Nội dung');
@define ('_gui','Gửi');
@define ('_nhaplai','Nhập lại');

@define ('_xinnhaphoten','Vui lòng nhập họ tên!');
@define ('_xinnhapdiachi','Vui lòng nhập địa chỉ!');
@define ('_xinnhapdt','Vui lòng nhập điện thoại!');
@define ('_dtkhonghople','Số điện thoại không hợp lệ!');
@define ('_emailkhonghople','Email không hợp lệ!');
@define ('_xinhaptieude','Vui lòng nhập chủ đề!');
@define ('_xinhapnoidung','Vui lòng nhập nội dung!');

?>